[build]
command = "npm run build"   # or "yarn build"
  publish = "dist"


[build.environment]
  NODE_VERSION = "20.9.0"  # ou la version de Node.js que vous utilisez
  NETLIFY_BUILD_IMAGE = "ubuntu-noble-24.04"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200